name = "new-test"
main = "src/worker.js"
compatibility_date = "2023-08-23"

[[rules]]
type = "ESModule"
globs = ["src/**"]

[[rules]]
type = "CommonJS"
globs = ["src/worker.js"]

[[rules]]
type = "CommonJS"
globs = ["src/app.js"]