name = "new-test"
type = "javascript"
compatibility_date = "2023-08-23"

[build]
command = "npm run build"
upload-format = "service-worker"

account_id = "93b80b8e065fc9dd5f2df65517849ee9"
workers_dev = true